package hr.foi.rampu.emedi.helpers

object MockDataSpecialization {
    val specializationList = arrayOf(
        "Select item",
        "Abdominalna kirurgija",
        "Alergologija i klinička imunologija",
        "Anesteziologija, reanimatologija i intenzivna medicina",
        "Dermatologija i venerologija",
        "Dječja i adolescentna psihijatrija",
        "Dječja kirurgija",
        "Endokrinologija i dijabetologija",
        "Epidemiologija",
        "Fizikalna medicina i rehabilitacija",
        "Gastroenterologija",
        "Gerijatrija",
        "Ginekologija i opstetricija",
        "Hematologija",
        "Hitna medicina",
        "Infektologija",
        "Internistička onkologija",
        "Javnozdravstvena medicina",
        "Kardiologija",
        "Kardiotorakalna kirurgija",
        "Klinička farmakologija s toksikologijom",
        "Klinička mikrobiologija",
        "Klinička radiologija",
        "Laboratorijska imunologija",
        "Maksilofacijalna kirurgija",
        "Medicina rada i športa",
        "Medicinska genetika",
        "Nefrologija",
        "Neurokirurgija",
        "Neurologija",
        "Nuklearna medicina",
        "Obiteljska medicina",
        "Oftalmologija i optometrija",
        "Onkologija i radioterapija",
        "Opća interna medicina",
        "Opća kirurgija",
        "Ortopedija i traumatologija",
        "Otorinolaringologija",
        "Patologija i citologija",
        "Pedijatrija",
        "Pedijatrijska infektologija",
        "Plastična, rekonstrukcijska i estetska kirurgija",
        "Psihijatrija",
        "Pulmologija",
        "Reumatologija",
        "Sudska medicina",
        "Školska i adolescentna medicina",
        "Transfuzijska medicina",
        "Urologija",
        "Vaskularna kirurgija"
    )
}